from abc import ABC, abstractmethod


class BaseDQEngine(ABC):
    @abstractmethod
    def schema(self, df, columns): ...
    @abstractmethod
    def not_null(self, df, columns): ...
    @abstractmethod
    def unique(self, df, columns): ...
    @abstractmethod
    def dtypes(self, df, rules): ...
